/* Generated By:JavaCC: Do not edit this line. wh0parserConstants.java */
package de.prodevmo.w0parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface wh0parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IN = 1;
  /** RegularExpression Id. */
  int OUT = 2;
  /** RegularExpression Id. */
  int VAR = 3;
  /** RegularExpression Id. */
  int EQUALS_ASSIGN = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int ZERO = 6;
  /** RegularExpression Id. */
  int ONE = 7;
  /** RegularExpression Id. */
  int NOTEQUALS = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int BEGIN = 11;
  /** RegularExpression Id. */
  int END = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int LEFT_BRACKET_ROUND = 15;
  /** RegularExpression Id. */
  int RIGHT_BRACKET_ROUND = 16;
  /** RegularExpression Id. */
  int IDENT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"in\"",
    "\"out\"",
    "\"var\"",
    "\"=\"",
    "\"+\"",
    "\"0\"",
    "\"1\"",
    "\"!=\"",
    "\"while\"",
    "\"do\"",
    "\"begin\"",
    "\"end\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<IDENT>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
